# Generated by Django 5.2.12 on 2026-03-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('policy_id', models.TextField()),
                ('cohort_year', models.IntegerField()),
                ('issue_age', models.IntegerField()),
                ('annual_premium', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'db_table': 'policies',
                'managed': False,
            },
        ),
    ]
